- name: Installing dependencies
  become: true
  apt:
    name: "{{item}}"
    state: present
    update_cache: true

  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - lsb-release
    - software-properties-common

- name: Adding GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adding docker repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Installing docker
  become: true
  apt:
    name: "{{item}}"
    state: latest
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose

- name: Ensuring the user is added to the docker group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true

# reset_connection doesn't support conditionals.
- name: Resetting connection so docker group is picked up
  meta: reset_connection

- name: Starting docker service
  service:
    name: docker
    state: started
    enabled: true
