- name: Opening firewall ports
  become: true
  ufw:
    rule: allow
    port: "{{ item }}"

  loop:
    - 22
    - 443
    - 80

- name: Setting firewall
  become: true
  ufw:
    state: enabled

- name: Disabling iptables
  become: true
  command: iptables -P INPUT ACCEPT
  tags: [never, disable-iptables]

- name: Disabling iptables
  become: true
  command: iptables -P FORWARD ACCEPT
  tags: [never, disable-iptables]

- name: Disabling iptables
  become: true
  command: iptables -P OUTPUT ACCEPT
  tags: [never, disable-iptables]

- name: Disabling iptables
  become: true
  command: iptables -F
  tags: [never, disable-iptables]

- name: Resetting connection
  meta: reset_connection
